### ISSUE TITLE
api19之后的版本，pinnedView不正常

### ISSUE THREAD

**Issue by enel1jk** [syupo/pinned#3]
应该是bringToFront()引起的。
bringToFront()方法的文档里有这句：“Prior to KITKAT this method should be followed by calls to requestLayout() and invalidate() on the view's parent to force the parent to redraw with the new child ordering.”但是调用文档里说的这两个方法后依然有问题。

求教。

**Comment by syupo** [comment]
确实有这个现象，bringToFront()配合requestLayout()、 invalidate() 或者 bringChildToFront()都有这个问题。解决办法：去掉之前的bringToFront()调用并Override dispatchDraw方法如下所示。
```java
	@Override
	protected void dispatchDraw(Canvas canvas) {
		Log.d(TAG, "dispatchDraw");
		super.dispatchDraw(canvas);
		drawChild(canvas, mPinnedView, getDrawingTime());
	}
```
但是不管之前的代码或此问题修正后的代码，都还有问题：
1. 如果视图发生了改变（如显示/隐藏等）会导致pinned的位置错乱。
2. 如果pinned 的覆盖的位置下面正好有其他控件，触摸pinned上对应的区域时则会触发此控件的事件调用

由于上述问题的存在，故抛弃了之前的做法，重写了这个项目 @shang1jk 可以 参看改项目下的share.pinned和share.pinned.simple目录
